add noguchi status
saxAllan/vet-app pull request #9
Opened 2021-11-21 11:48 UTC by nogtty0

2021-11-21 11:57 UTC, saxAllan requested changes
status.md 参考サイトを載せてくれたのはありがたい（後学のためになる）んですが、それを参考に「何をしたのか」が書いてないのでこの大量のファイル追加がなんなのか判断がつきません。

2021-11-21 11:57 UTC, saxAllan commented on status.md
> +    - https://e-seventh.com/laravel-jetstream-install/を参考にしました．
ここを参考に「何をしたのか」がわかりません。

2021-11-21 12:05 UTC, nogtty0 commented on status.md
> +    - https://e-seventh.com/laravel-jetstream-install/を参考にしました．
composerでJetStreamをインストールしました．

2021-11-21 12:09 UTC, saxAllan commented on status.md
> +    - https://e-seventh.com/laravel-jetstream-install/を参考にしました．
Change requestをしてるので、それを意図を持ってdenyするか、受け入れて修整するかしてくれないとapproveできません。
それに本来ここに書くべきことではないですが、グループにも書いたとおり昨日の僕のPRを誰もapproveしてないので、確実にコンフリクトするので頑張れ。

2021-11-22 03:26 UTC, saxAllan approved these changes

2021-11-22 03:27 UTC, merged